config/routes.rb
Rails.application.routes.draw do
  resources :webpages
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/webpage.rb
class Webpage < ApplicationRecord
  def body
    Nokogiri::HTML(raw_html).css("body").to_s
  end

  def head
    Nokogiri::HTML(raw_html).xpath("//head").to_s
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/webpages_controller.rb
require "net/http"

class WebpagesController < ApplicationController
  before_action :set_webpage, only: %i[ show edit update destroy ]

  # GET /webpages or /webpages.json
  def index
    @webpages = Webpage.all
  end

  # GET /webpages/1 or /webpages/1.json
  def show
  end

  # GET /webpages/new
  def new
    @webpage = Webpage.new
  end

  # GET /webpages/1/edit
  def edit
  end

  # POST /webpages or /webpages.json
  def create
    @webpage = Webpage.new(webpage_params)

    @webpage.raw_html = get_raw_html

    respond_to do |format|
      if @webpage.save
        format.html { redirect_to webpage_url(@webpage), notice: "Webpage was successfully created." }
        format.json { render :show, status: :created, location: @webpage }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @webpage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /webpages/1 or /webpages/1.json
  def update
    respond_to do |format|
      if @webpage.update(webpage_params)
        format.html { redirect_to webpage_url(@webpage), notice: "Webpage was successfully updated." }
        format.json { render :show, status: :ok, location: @webpage }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @webpage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /webpages/1 or /webpages/1.json
  def destroy
    @webpage.destroy

    respond_to do |format|
      format.html { redirect_to webpages_url, notice: "Webpage was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

    def get_raw_html
      Net::HTTP.get(URI(@webpage.url)).force_encoding("UTF-8")
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_webpage
      @webpage = Webpage.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def webpage_params
      params.require(:webpage).permit(:raw_html, :url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/webpages_helper.rb
module WebpagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ScraperOnRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/webpages/_form.html.erb
<%= form_with(model: webpage) do |form| %>
  <% if webpage.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(webpage.errors.count, "error") %> prohibited this webpage from being saved:</h2>

      <ul>
        <% webpage.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :raw_html, style: "display: block" %>
    <%= form.text_area :raw_html %>
  </div>

  <div>
    <%= form.label :url, style: "display: block" %>
    <%= form.text_field :url %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/webpages/_webpage.html.erb
<div id="<%= dom_id webpage %>">
  <p>
  <strong>Url:</strong>
  <%= webpage.url %>
  </p>


  <p>
  <strong>head:</strong>
  <%= webpage.head %>
  </p>
  <p>
  <strong>body:</strong>
  <%= webpage.body %>
  </p>
</div>

app/views/webpages/edit.html.erb
<h1>Editing webpage</h1>

<%= render "form", webpage: @webpage %>

<br>

<div>
  <%= link_to "Show this webpage", @webpage %> |
  <%= link_to "Back to webpages", webpages_path %>
</div>

app/views/webpages/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Webpages</h1>

<div id="webpages">
  <% @webpages.each do |webpage| %>
    <%= render webpage %>
    <p>
      <%= link_to "Show this webpage", webpage %>
    </p>
  <% end %>
</div>

<%= link_to "New webpage", new_webpage_path %>

app/views/webpages/new.html.erb
<h1>New webpage</h1>

<%= render "form", webpage: @webpage %>

<br>

<div>
  <%= link_to "Back to webpages", webpages_path %>
</div>

app/views/webpages/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @webpage %>

<div>
  <%= link_to "Edit this webpage", edit_webpage_path(@webpage) %> |
  <%= link_to "Back to webpages", webpages_path %>

  <%= button_to "Destroy this webpage", @webpage, method: :delete %>
</div>